### PR TITLE
modifies error messages, removes irrelevant files, adds tests

### PR DESCRIPTION
**Pull request by solegalli**
Hi @Morgan-Sell 

I add the changes needed to complete this PR.

Could you review the files and merge?

this will automatically commit the changes to the PR in the main repo, and then we can close the issue.

Thank you!

### CODE REVIEW

**Comment by Morgan-Sell** [comment]
@solegalli , it looks good to me! Thanks for the help ;)

Do you prefer that I select "Merge pull request" or "Squash and Merge"? I see that the feature-engine docs mentions "Squash and Merge"; however, I see the benefit of having the commits as separate steps.

Once I know, I'll merge the branch with master.

**Comment by solegalli** [comment]
Hi @Morgan-Sell 

In short, it doesn't matter.

In the main repo we do squash and merge so that every pull request is summarized in 1 commit that just references the new functionality.

Here, we can keep the detail (not squash) so that we know what's been happening.

Cheers

**Comment by Morgan-Sell** [comment]
Thanks for the explanation, @solegalli!

After switching to the `main` branch, do I now run `git pull --rebase upstream main` to obtain the updates?

**Comment by solegalli** [comment]
> r switching to th

yes :)

**Pull request merged**
